### PR TITLE
I organized all the packages and created your daily questions

### PR DESCRIPTION
**Pull request by emcemen**
this one is the last one I will gone send a image how its seen now on Inttelij too more organized
We can add daily packages for questions and when its solved the person who created the question can take the java class to its own package 
ex: alper_question_08_27 when its solved  who created the question(emre) will cary it to --->Logic2 package  and then delete empty daily question package( alper_question_08_27 )
and also we will add questions daily too if we have different solutions we can commit and update it

### CODE REVIEW

**Comment by Alpimax** [comment]
you got approval

**Comment by emcemen** [comment]
I fixed the conflict in my local repository and now it Is able to merge

**Comment by emcemen** [comment]
you can add your review and check after that you can merge it

**Comment by Alpimax** [comment]
okay let's me check...

**Pull request merged**
